// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_rz1AMmP3veJsiVDoioXRsR9qcK4zFAk',
    appId: '1:695707424994:web:82163e864887164ef9a6bb',
    messagingSenderId: '695707424994',
    projectId: 'dingonew-6e7f1',
    authDomain: 'dingonew-6e7f1.firebaseapp.com',
    storageBucket: 'dingonew-6e7f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPvvUQIdtOyYslwL1ro0zSNAJkuwkQLGA',
    appId: '1:695707424994:android:96570012847cd1eaf9a6bb',
    messagingSenderId: '695707424994',
    projectId: 'dingonew-6e7f1',
    storageBucket: 'dingonew-6e7f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO3hW5w8FOz4Ipp8j8h8sgiECEktNcLvI',
    appId: '1:695707424994:ios:f6b5aae65880ee1af9a6bb',
    messagingSenderId: '695707424994',
    projectId: 'dingonew-6e7f1',
    storageBucket: 'dingonew-6e7f1.appspot.com',
    iosBundleId: 'com.example.dingoNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO3hW5w8FOz4Ipp8j8h8sgiECEktNcLvI',
    appId: '1:695707424994:ios:dbee1e0b52b40a4af9a6bb',
    messagingSenderId: '695707424994',
    projectId: 'dingonew-6e7f1',
    storageBucket: 'dingonew-6e7f1.appspot.com',
    iosBundleId: 'com.example.dingoNew.RunnerTests',
  );
}
